"""Оригинальная анимация: бриф -> раскадровка -> генерация -> сборка в After Effects.

Схема работы:
    1. brief.yaml     — формат, персонаж, тон, длина
    2. shots.json     — раскадровка: сцены с промптами и таймингом
    3. генерация      — Higgsfield по промптам из раскадровки
    4. assemble.jsx   — скрипт, который собирает готовые сцены в композицию AE

Модель тут ничего не генерирует сама: она отдаёт схему раскадровки и
собирает по ней скрипт сборки. Промпты пишутся отдельно (руками или
через Claude по шаблону из prompt_template).
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field, asdict
from pathlib import Path

SHOTS_SCHEMA_VERSION = 1

# Вертикаль под шортформ.
COMP_WIDTH = 1080
COMP_HEIGHT = 1920
COMP_FPS = 30


@dataclass
class Shot:
    """Одна сцена раскадровки."""

    id: str
    prompt: str                      # что генерировать
    duration: float                  # длина сцены в секундах
    caption: str = ""                # подпись на экране
    camera: str = ""                 # движение камеры (Higgsfield motion preset)
    character: str = ""              # Soul ID персонажа, если сцена с ним
    file: str = ""                   # заполняется после генерации


@dataclass
class Brief:
    """Формат целиком."""

    title: str
    logline: str = ""
    character: str = ""
    style: str = ""
    tone: str = ""
    target_seconds: float = 30.0
    shots: list[Shot] = field(default_factory=list)


def load_brief(path: Path) -> Brief:
    import yaml

    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    shots = [Shot(**s) for s in data.pop("shots", [])]
    return Brief(**data, shots=shots)


def save_shots(brief: Brief, path: Path) -> None:
    payload = {
        "version": SHOTS_SCHEMA_VERSION,
        "title": brief.title,
        "comp": {"width": COMP_WIDTH, "height": COMP_HEIGHT, "fps": COMP_FPS},
        "shots": [asdict(s) for s in brief.shots],
    }
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")


def load_shots(path: Path) -> dict:
    data = json.loads(path.read_text(encoding="utf-8"))
    if data.get("version") != SHOTS_SCHEMA_VERSION:
        raise ValueError(f"неизвестная версия раскадровки: {data.get('version')}")
    return data


def prompt_template(brief: Brief, count: int) -> str:
    """Заготовка запроса к модели на раскадровку.

    Отдаётся как текст: скопировать в Claude, получить сцены, разложить
    обратно в brief.yaml. Промпты под видеогенерацию пишутся по-английски —
    модели на нём заметно точнее.
    """
    return f"""Разбей формат на {count} сцен под вертикальный ролик {brief.target_seconds:.0f} секунд.

Формат:   {brief.title}
Логлайн:  {brief.logline}
Персонаж: {brief.character}
Стиль:    {brief.style}
Тон:      {brief.tone}

Для каждой сцены дай:
  id        — короткий слаг
  prompt    — промпт на английском под видеогенерацию: что в кадре,
              освещение, материал, настроение. Без имён реальных людей.
  duration  — секунды, сумма всех сцен = {brief.target_seconds:.0f}
  caption   — подпись на экране, если нужна
  camera    — движение камеры (push in, orbit, handheld, static, crane)
  character — слаг персонажа, если он в кадре

Первая сцена — крючок: она должна читаться за полсекунды без звука.
Верни YAML под ключом shots."""


def build_aescript(shots_data: dict, footage_dir: Path) -> str:
    """Собрать ExtendScript, который строит композицию из готовых сцен."""
    comp = shots_data.get("comp", {})
    width = comp.get("width", COMP_WIDTH)
    height = comp.get("height", COMP_HEIGHT)
    fps = comp.get("fps", COMP_FPS)

    shots = [s for s in shots_data.get("shots", []) if s.get("file")]
    if not shots:
        raise ValueError("в раскадровке нет сцен с заполненным полем file")

    total = sum(float(s["duration"]) for s in shots)
    title = shots_data.get("title", "mily_comp")

    payload = json.dumps(
        [
            {
                "file": str((footage_dir / s["file"]).resolve()),
                "duration": float(s["duration"]),
                "caption": s.get("caption", ""),
            }
            for s in shots
        ],
        ensure_ascii=True,
    )

    return _JSX_TEMPLATE % {
        "title": json.dumps(title, ensure_ascii=True),
        "width": width,
        "height": height,
        "fps": fps,
        "total": f"{total:.3f}",
        "shots": payload,
    }


# ExtendScript у After Effects — старый диалект, поэтому ни let/const,
# ни стрелок, ни JSON.parse на древних версиях. Данные вшиваем литералом.
_JSX_TEMPLATE = """// Generated by mily. In After Effects: File > Scripts > Run Script File
(function () {
    var TITLE = %(title)s;
    var WIDTH = %(width)d;
    var HEIGHT = %(height)d;
    var FPS = %(fps)d;
    var TOTAL = %(total)s;
    var SHOTS = %(shots)s;

    app.beginUndoGroup("mily: assemble");

    var comp = app.project.items.addComp(TITLE, WIDTH, HEIGHT, 1, TOTAL, FPS);
    comp.openInViewer();

    var cursor = 0;

    for (var i = 0; i < SHOTS.length; i++) {
        var shot = SHOTS[i];
        var file = new File(shot.file);

        if (!file.exists) {
            $.writeln("missing file, skipped: " + shot.file);
            continue;
        }

        var io = new ImportOptions(file);
        var footage = app.project.importFile(io);
        var layer = comp.layers.add(footage);

        layer.startTime = cursor;
        layer.inPoint = cursor;
        layer.outPoint = cursor + shot.duration;

        // fill the vertical frame by the larger side
        var sx = WIDTH / layer.source.width;
        var sy = HEIGHT / layer.source.height;
        var scale = Math.max(sx, sy) * 100;
        layer.property("Scale").setValue([scale, scale]);

        // short overlap so cuts do not read as hard splices
        if (i > 0) {
            var op = layer.property("Opacity");
            op.setValueAtTime(cursor, 0);
            op.setValueAtTime(cursor + 0.12, 100);
        }

        if (shot.caption && shot.caption.length > 0) {
            var text = comp.layers.addText(shot.caption);
            var doc = text.property("Source Text").value;
            doc.fontSize = 72;
            doc.justification = ParagraphJustification.CENTER_JUSTIFY;
            doc.applyFill = true;
            doc.fillColor = [1, 1, 1];
            text.property("Source Text").setValue(doc);
            text.property("Position").setValue([WIDTH / 2, HEIGHT * 0.82]);
            text.startTime = cursor;
            text.inPoint = cursor;
            text.outPoint = cursor + shot.duration;
        }

        cursor += shot.duration;
    }

    app.endUndoGroup();
    $.writeln("assembled shots: " + SHOTS.length + ", length " + cursor + "s");
})();
"""
